### ISSUE TITLE
Please Update for SDK 1.4.0

### ISSUE THREAD

**Issue by kbooth-insight** [sparkfunX/A111_Pulsed_Radar_Breakout#6]
The code doesn't build with the most recent SDK:

```
pi@raspberrypi:~/evk_service_linux_armv7l_xc111_r4a_xr111-3_r1c_a111_r2c $ make
    Compiling acc_board_rpi_sparkx.c
source/acc_board_rpi_sparkx.c: In function ‘acc_board_init’:
source/acc_board_rpi_sparkx.c:177:2: error: too few arguments to function ‘acc_driver_gpio_linux_sysfs_register’
  acc_driver_gpio_linux_sysfs_register(28);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from source/acc_board_rpi_sparkx.c:12:0:
include/acc_driver_gpio_linux_sysfs.h:51:13: note: declared here
 extern void acc_driver_gpio_linux_sysfs_register(uint_fast16_t pin_count, gpio_t *gpio_mem);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
makefile:60: recipe for target 'out/obj/acc_board_rpi_sparkx.o' failed
```

I tried setting up the new gpio_t param myself, and I end up hard-locking the Pi.

**Comment by jimblom** [comment]
Thanks for the heads up!

I've pushed some new changes to source/acc_board_rpi_sparkx.c in commit dbbd525. Should update the addon files to work with SDK 1.4.0.

Feel free to re-open if it's still giving you trouble.

**Comment by kbooth-insight** [comment]
Thanks much for updating!

I'm not sure if I should ask this here or over at the sparkfun forums, but after pulling this update and building, I seem to get calibration errors.  The sensor initializes correctly it seems, 

Here is some example output:
```
pi@raspberrypi:~/evk_service_linux_armv7l_xc111_r4a_xr111-3_r1c_a111_r2c/out $ ./sparkx_detector_distance 
Acconeer software version v1.4.0
Acconeer RSS version 1.0
20:00:23.271 [10508] (I) (rss): Radar system services activated

A111 Initialized

Press ENTER to run distance detection...
Running distance peak detector in blocking mode
20:00:29.367 [10508] (E) (sensor_protocol): Timeout waiting for interrupt.
20:00:29.367 [10508] (E) (sensor_protocol): Timeout waiting for indication on sensor 1.
20:00:29.368 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:29.368 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:29.368 [10508] (I) (sensor_protocol): Run_status running at : 1c2
<snip>
20:00:29.373 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:29.373 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:29.373 [10508] (I) (sensor_protocol): Interrupt_status_register: 80
20:00:29.373 [10508] (I) (sensor_protocol): WakeupInput[7..0]_wakeup_config: 0 24 0 0 0 0 0 0
20:00:29.373 [10508] (I) (sensor_protocol): Inputmux_wakeupinput[7..0]_config : 0 13 0 0 0 0 0 8
20:00:29.373 [10508] (I) (sensor_protocol): Timer[3..0]_wakeup_config: 0 0 0 0
20:00:29.374 [10508] (I) (sensor_protocol): asic_identity_number: 4370, run_status: 1474, interrupt_status: 80, Scratchpad Config 7: 3
20:00:29.374 [10508] (I) (sensor_protocol): Wakeup_status0_register: 1
20:00:29.374 [10508] (I) (sensor_protocol): asic_error_status : 0
20:00:29.374 [10508] (I) (sensor_protocol): Stack_level_status_register: 0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 0: Addr=450
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 1: Addr=449 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 2: Addr=468 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 3: Addr=0 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 4: Addr=0 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 5: Addr=0 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 6: Addr=0 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): Stack level 7: Addr=0 Loop=0
20:00:29.374 [10508] (I) (sensor_protocol): vco_cbank_config: 4
20:00:29.374 [10508] (I) (sensor_protocol): pll_config: 127
20:00:29.374 [10508] (I) (sensor_protocol): Pll_div_config: 9
20:00:29.375 [10508] (E) (cbank_calibration_manager): Failed to retrieve indication.
20:00:29.375 [10508] (E) (cbank_calibration_manager): Failed to get result.
20:00:29.375 [10508] (E) (core_a111_r2c): CBank calibration failure.
20:00:29.375 [10508] (E) (session_sweep_and_processing): Sensor calibration failure for sensor 1.
Free space absolute offset: 4294967295 mm
Actual start: 4294967295 mm
Actual length: 4294967295 mm
Actual end: 4294967295 mm

20:00:29.375 [10508] (E) (service): Configuration: Invalid handle.
acc_service_activate() failed
20:00:29.375 [10508] (E) (service): Configuration: Invalid handle.
Running distance peak detector in blocking mode failed
Press ENTER to calculate THRESHOLD and run peak detection...
Running distance peak detector in blocking mode with estimated threshold
20:00:42.455 [10508] (E) (sensor_protocol): Timeout waiting for interrupt.
20:00:42.455 [10508] (E) (sensor_protocol): Timeout waiting for indication on sensor 1.
20:00:42.455 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.455 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.455 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.455 [10508] (I) (sensor_protocol): Run_status running at : 1c2
<snip>
20:00:42.460 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.460 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.460 [10508] (I) (sensor_protocol): Run_status running at : 1c2
20:00:42.460 [10508] (I) (sensor_protocol): Interrupt_status_register: 80
20:00:42.461 [10508] (I) (sensor_protocol): WakeupInput[7..0]_wakeup_config: 0 24 0 0 0 0 0 0
20:00:42.461 [10508] (I) (sensor_protocol): Inputmux_wakeupinput[7..0]_config : 0 13 0 0 0 0 0 8
20:00:42.461 [10508] (I) (sensor_protocol): Timer[3..0]_wakeup_config: 0 0 0 0
20:00:42.461 [10508] (I) (sensor_protocol): asic_identity_number: 4370, run_status: 1474, interrupt_status: 80, Scratchpad Config 7: 3
20:00:42.461 [10508] (I) (sensor_protocol): Wakeup_status0_register: 1
20:00:42.461 [10508] (I) (sensor_protocol): asic_error_status : 0
20:00:42.461 [10508] (I) (sensor_protocol): Stack_level_status_register: 0
20:00:42.461 [10508] (I) (sensor_protocol): Stack level 0: Addr=450
20:00:42.461 [10508] (I) (sensor_protocol): Stack level 1: Addr=449 Loop=0
20:00:42.461 [10508] (I) (sensor_protocol): Stack level 2: Addr=468 Loop=0
20:00:42.461 [10508] (I) (sensor_protocol): Stack level 3: Addr=0 Loop=0
20:00:42.462 [10508] (I) (sensor_protocol): Stack level 4: Addr=0 Loop=0
20:00:42.462 [10508] (I) (sensor_protocol): Stack level 5: Addr=0 Loop=0
20:00:42.462 [10508] (I) (sensor_protocol): Stack level 6: Addr=0 Loop=0
20:00:42.462 [10508] (I) (sensor_protocol): Stack level 7: Addr=0 Loop=0
20:00:42.462 [10508] (I) (sensor_protocol): vco_cbank_config: 4
20:00:42.462 [10508] (I) (sensor_protocol): pll_config: 127
20:00:42.462 [10508] (I) (sensor_protocol): Pll_div_config: 9
20:00:42.462 [10508] (E) (cbank_calibration_manager): Failed to retrieve indication.
20:00:42.462 [10508] (E) (cbank_calibration_manager): Failed to get result.
20:00:42.462 [10508] (E) (core_a111_r2c): CBank calibration failure.
20:00:42.462 [10508] (E) (session_sweep_and_processing): Sensor calibration failure for sensor 1.
Free space absolute offset: 4294967295 mm
Actual start: 4294967295 mm
Actual length: 4294967295 mm
Actual end: 4294967295 mm

Estimating threshold...
20:00:42.462 [10508] (E) (service): Configuration: Invalid handle.
20:00:42.462 [10508] (E) (acc_detector_distance_peak): Threshold estimation update failed
Estimating threshold done...

Press ENTER to measure threshold-ed distance
Then press CTRL+C to STOP

20:00:46.345 [10508] (E) (service): Configuration: Invalid handle.
acc_service_activate() failed
20:00:46.345 [10508] (W) (acc_detector_distance_peak): Detector is already inactive
20:00:46.345 [10508] (E) (service): Configuration: Invalid handle.
20:00:46.345 [10508] (I) (rss): Radar system services deactivated
```

Any help would be greatly appreciated!

**Comment by jimblom** [comment]
Oof, at a glance, I'm not sure -- haven't seen those errors before.

If you don't mind opening a new issue with this, I'd be happy to look into it.
